---
  - name: set ip adress for the cluster to /etc/hosts
    blockinfile:
      state: present
      insertafter: EOF
      dest: "/etc/hosts"
      content: |
        {{ lookup('file', 'templates/hosts.j2') }}
  - name: Remove lines with 127 from hosts
    lineinfile:
      dest: "/etc/hosts"
      regexp: "^127.0.0.1|^127.0.1.1"
      state: absent
    tags: removelocalhost
  - name: copy pulsar
    copy:
      src: "{{ apache_pulsar_arch }}"
      dest: "/opt"
      force: no
  - name: Unarchive a apache pulsar
    unarchive:
      src: "/opt/{{ apache_pulsar_arch }}"
      dest: /opt
      remote_src: yes
    register: apache_pulsar_root_dir
  - name: copy zookeeper conf to pulsar
    blockinfile:
      state: present
      insertafter: EOF
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/zookeeper.conf"
      content: |
        {{ lookup('file', 'templates/zookeeper.j2') }}
    when: "'zookeeper' in group_names"
  - name: Create data dirs
    file:
      path: "{{ item.path }}"
      state: directory
      mode: "{{ item.mode | default(omit) }}"
    loop:
      - path: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/data/"
#        mode: a+rX
  - name: Create zookeeper dirs
    file:
      path: "{{ item.path }}"
      state: directory
      mode: "{{ item.mode | default(omit) }}"
    loop:
      - path: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/data/zookeeper"
    #        mode: a+rX
    when: "'zookeeper' in group_names"
  - name: Set cluster ID
    copy:
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/data/zookeeper/myid"
      content: "{{ inventory_hostname |  replace('zookeeper' ,'' ) | replace('.pulsar' ,'')  }}"
    when: "'zookeeper' in group_names"

  - name: Remove lines with zkServers from bookkeeper conf
    lineinfile:
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/bookkeeper.conf"
      regexp: "^zkServers"
      state: absent
  - name: set zkServers ensemble to bookkeeper conf
    lineinfile:
      state: present
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/bookkeeper.conf"
      line: |
        {{ lookup('file', 'templates/bookeeper.j2') }}
    when: "'broker' in group_names"
  - name: Remove lines with advertisedAddress from bookkeeper conf
    lineinfile:
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/bookkeeper.conf"
      regexp: "^advertisedAddress"
      state: absent
    when: "'broker' in group_names"
  - name: set advertisedAddress ensemble to bookkeeper conf
    lineinfile:
      state: present
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/bookkeeper.conf"
      line: |
        {{ lookup('file', 'templates/bookie.j2') }}
    when: "'broker' in group_names"
  - name: remove useHostNameAsBookieID
    lineinfile:
      state: absent
      regexp: "^useHostNameAsBookieID"
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/bookkeeper.conf"
    when: "'broker' in group_names"
  - name: set useHostNameAsBookieID to true in bookkeper conf
    lineinfile:
      state: present
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/bookkeeper.conf"
      line: |
        useHostNameAsBookieID=false
    when: "'broker' in group_names"
  - name: set quorumListenOnAllIPs to true in zookeeper conf
    lineinfile:
      state: present
      dest: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/conf/zookeeper.conf"
      line: |
        quorumListenOnAllIPs=true
    when: "'zookeeper' in group_names"


  - name: Start zookeeper.
    shell:
      cmd: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/bin/pulsar-daemon start zookeeper"
    when: "'zookeeper' in group_names"

  - name: Initialise metadata.
    shell:
      cmd: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/bin/pulsar initialize-cluster-metadata \
                                                                              --cluster pulsar-cluster-1 \
                                                                              --zookeeper zookeeper1.pulsar:2181,zookeeper2.pulsar:2181,zookeeper3.pulsar:2181 \
                                                                              --configuration-store zookeeper1.pulsar:2181,zookeeper2.pulsar:2181,zookeeper3.pulsar:2181  \
                                                                              --web-service-url http://broker1.pulsar:8080,broker2.pulsar:8080,broker3.pulsar:8080 \
                                                                              --web-service-url-tls https://broker1.pulsar:8443,broker2.pulsar:8443,broker3.pulsar:8443 \
                                                                              --broker-service-url pulsar://broker1.pulsar:6650,broker2.pulsar:6650,broker3.pulsar:6650 \
                                                                              --broker-service-url-tls pulsar+ssl://broker1.pulsar:6651,broker2.pulsar:6651,broker3.pulsar:6651"
    when: inventory_hostname == groups['zookeeper'][0]
    tags: metadata

  - name: Start bookeeper.
    shell:
      cmd: "/opt/{{ apache_pulsar_arch | replace('-bin.tar.gz' ,'') }}/bin/pulsar-daemon start bookie"
    when: "'broker' in group_names"
  - name: Display arch
    debug:
      msg: "The name of dir is is {{ inventory_hostname | replace('pulsar' ,'') | replace('zookeeper' ,'') }} "
